### ISSUE TITLE
data validation

### ISSUE THREAD

**Issue by gedw99** [ConnectEverything/nats-by-example#112]
One thing i keep on getting asked is "whats is the best way to do validation"...

This is really for Producers / Mutations, but also perhaps for Consumers too.

I tend to go for either JSON Schema, just like NATS JSM uses.

But there seems to be pretty good frameworks too:

i see many people using outside NATS is https://ajv.js.org/guide/schema-language.html.

There is 2 options:
- JSON Schema
- JSON Type Definition

Language for JSON Type Def:

https://github.com/orgs/jsontypedef/repositories

https://github.com/jsontypedef/json-typedef-go

**Comment by scottf** [comment]
@gedw99 Moving this question to the [Architecture and Design repo](https://github.com/nats-io/nats-architecture-and-design) where this discussion can be better addressed.
