### ISSUE TITLE
Auth callout  centralized example not working

### ISSUE THREAD

**Issue by pyxiscloud** [ConnectEverything/nats-by-example#167]
Hi
It's not working
got error "nkeys: could not decrypt input"

Can you check and fix please?

**Comment by bruth** [comment]
Hi @pyxiscloud, to confirm you cloned the repo and ran `nbe run examples/auth/callout/cli` and you got an error?

**Comment by pyxiscloud** [comment]
with nbe got this:
![image](https://github.com/ConnectEverything/nats-by-example/assets/14041313/48c53260-02d0-47e7-9401-034d83216033)

**Comment by pyxiscloud** [comment]
![image](https://github.com/ConnectEverything/nats-by-example/assets/14041313/34dda84e-71dc-4796-a724-8ac5f119a873)

**Comment by pyxiscloud** [comment]
fixed it with go get -u all
