### ISSUE TITLE
[C# .NET V2] Example for List subjects for a specific stream

### ISSUE THREAD

**Issue by scottf** [ConnectEverything/nats-by-example#217]
Create an example that demonstrates how to list the subjects for a stream
Directory is jetstream\list-subjects

**Comment by mtmk** [comment]
not sure if this is implemented. We have a [GetStream() call](https://github.com/nats-io/nats.net.v2/blob/f6c6419f34741dc9dabfbe400c4861d25901a579/src/NATS.Client.JetStream/INatsJSContext.cs#L250), is that enough? Or is there a specific API to pull just the subjects out?

**Comment by scottf** [comment]
Yes, the GetStreamAsync with a StreamInfoRequest that has a SubjectsFilter.
