### ISSUE TITLE
Not using Jetstream and really old

### ISSUE THREAD

**Issue by gedw99** [ConnectEverything/nats-by-example#231]
### Observed behavior

https://github.com/ConnectEverything/nats-by-example/blob/main/examples/auth/callout/cli/service/main.go

Not using js ?
Old code ?

I am trying build adapters for sure call-out to work with different oidc system like Apple and Google and wanted to add these but this code is not up to date ?

### Expected behavior

Js

### Server and client version

Sane as repo.

**Comment by Jarema** [comment]
Hey!

This is just an example that shows how to interact with auth callouts.
How you want to handle persistance and other logic is up to you, and also depends a lot on use case.
You can also check out latest video about auth callouts: https://www.youtube.com/watch?v=VvGxrT-jv64

**Comment by scottf** [comment]
@gedw99 Closing this. Auth Callout requires JetStream. If you can give more specifics on the issue you are having with this example please continue to comment and @ me so I'm notified. You may also want to post something in [NATS Slack](https://slack.nats.io/) to see if other folks have done what you are attempting to do.
